# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'domeMain.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.widget_player = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_player.sizePolicy().hasHeightForWidth())
        self.widget_player.setSizePolicy(sizePolicy)
        self.widget_player.setObjectName("widget_player")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_player)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.glFrame = QtWidgets.QFrame(self.widget_player)
        self.glFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glFrame.sizePolicy().hasHeightForWidth())
        self.glFrame.setSizePolicy(sizePolicy)
        self.glFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.glFrame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.glFrame.setAutoFillBackground(False)
        self.glFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.glFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.glFrame.setObjectName("glFrame")
        self.verticalLayout_2.addWidget(self.glFrame)
        self.widget_timeline = QtWidgets.QWidget(self.widget_player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_timeline.sizePolicy().hasHeightForWidth())
        self.widget_timeline.setSizePolicy(sizePolicy)
        self.widget_timeline.setObjectName("widget_timeline")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_timeline)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_slider = QtWidgets.QSlider(self.widget_timeline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_slider.sizePolicy().hasHeightForWidth())
        self.frame_slider.setSizePolicy(sizePolicy)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.horizontalLayout.addWidget(self.frame_slider)
        self.bn_slow = QtWidgets.QToolButton(self.widget_timeline)
        self.bn_slow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bn_slow.setArrowType(QtCore.Qt.NoArrow)
        self.bn_slow.setObjectName("bn_slow")
        self.horizontalLayout.addWidget(self.bn_slow)
        self.bn_play = QtWidgets.QToolButton(self.widget_timeline)
        self.bn_play.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bn_play.setArrowType(QtCore.Qt.NoArrow)
        self.bn_play.setObjectName("bn_play")
        self.horizontalLayout.addWidget(self.bn_play)
        self.bn_fast = QtWidgets.QToolButton(self.widget_timeline)
        self.bn_fast.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bn_fast.setArrowType(QtCore.Qt.NoArrow)
        self.bn_fast.setObjectName("bn_fast")
        self.horizontalLayout.addWidget(self.bn_fast)
        self.edit_cur_frame = QtWidgets.QLineEdit(self.widget_timeline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_cur_frame.sizePolicy().hasHeightForWidth())
        self.edit_cur_frame.setSizePolicy(sizePolicy)
        self.edit_cur_frame.setMaximumSize(QtCore.QSize(100, 30))
        self.edit_cur_frame.setAutoFillBackground(False)
        self.edit_cur_frame.setMaxLength(8)
        self.edit_cur_frame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_cur_frame.setObjectName("edit_cur_frame")
        self.horizontalLayout.addWidget(self.edit_cur_frame)
        self.label_frame = QtWidgets.QLabel(self.widget_timeline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_frame.sizePolicy().hasHeightForWidth())
        self.label_frame.setSizePolicy(sizePolicy)
        self.label_frame.setTextFormat(QtCore.Qt.AutoText)
        self.label_frame.setObjectName("label_frame")
        self.horizontalLayout.addWidget(self.label_frame)
        self.edit_max_frame = QtWidgets.QLineEdit(self.widget_timeline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_max_frame.sizePolicy().hasHeightForWidth())
        self.edit_max_frame.setSizePolicy(sizePolicy)
        self.edit_max_frame.setMaximumSize(QtCore.QSize(100, 30))
        self.edit_max_frame.setReadOnly(True)
        self.edit_max_frame.setClearButtonEnabled(False)
        self.edit_max_frame.setObjectName("edit_max_frame")
        self.horizontalLayout.addWidget(self.edit_max_frame)
        self.verticalLayout_2.addWidget(self.widget_timeline)
        self.mainLayout.addWidget(self.widget_player)
        self.widget_split = QtWidgets.QWidget(self.centralwidget)
        self.widget_split.setObjectName("widget_split")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_split)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bn_showcontrol = QtWidgets.QToolButton(self.widget_split)
        self.bn_showcontrol.setCheckable(True)
        self.bn_showcontrol.setChecked(True)
        self.bn_showcontrol.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bn_showcontrol.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bn_showcontrol.setArrowType(QtCore.Qt.RightArrow)
        self.bn_showcontrol.setObjectName("bn_showcontrol")
        self.verticalLayout_3.addWidget(self.bn_showcontrol)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.mainLayout.addWidget(self.widget_split)
        self.widget_control = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_control.sizePolicy().hasHeightForWidth())
        self.widget_control.setSizePolicy(sizePolicy)
        self.widget_control.setObjectName("widget_control")
        self.layout_control = QtWidgets.QVBoxLayout(self.widget_control)
        self.layout_control.setObjectName("layout_control")
        self.group_model = QtWidgets.QGroupBox(self.widget_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_model.sizePolicy().hasHeightForWidth())
        self.group_model.setSizePolicy(sizePolicy)
        self.group_model.setFlat(False)
        self.group_model.setObjectName("group_model")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_model)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.list_model = QtWidgets.QTreeWidget(self.group_model)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_model.sizePolicy().hasHeightForWidth())
        self.list_model.setSizePolicy(sizePolicy)
        self.list_model.setObjectName("list_model")
        self.list_model.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.list_model)
        self.layout_control.addWidget(self.group_model)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_control.addItem(spacerItem1)
        self.group_cam = QtWidgets.QGroupBox(self.widget_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_cam.sizePolicy().hasHeightForWidth())
        self.group_cam.setSizePolicy(sizePolicy)
        self.group_cam.setObjectName("group_cam")
        self.gridLayout = QtWidgets.QGridLayout(self.group_cam)
        self.gridLayout.setObjectName("gridLayout")
        self.label_y = QtWidgets.QLabel(self.group_cam)
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 5, 1, 1, 1)
        self.label_z = QtWidgets.QLabel(self.group_cam)
        self.label_z.setObjectName("label_z")
        self.gridLayout.addWidget(self.label_z, 5, 2, 1, 1)
        self.label_xrot = QtWidgets.QLabel(self.group_cam)
        self.label_xrot.setObjectName("label_xrot")
        self.gridLayout.addWidget(self.label_xrot, 2, 0, 1, 1)
        self.xEdit = QtWidgets.QDoubleSpinBox(self.group_cam)
        self.xEdit.setMinimum(-200.0)
        self.xEdit.setMaximum(200.0)
        self.xEdit.setObjectName("xEdit")
        self.gridLayout.addWidget(self.xEdit, 6, 0, 1, 1)
        self.zRotEdit = QtWidgets.QDoubleSpinBox(self.group_cam)
        self.zRotEdit.setMaximum(360.0)
        self.zRotEdit.setObjectName("zRotEdit")
        self.gridLayout.addWidget(self.zRotEdit, 4, 2, 1, 1)
        self.zEdit = QtWidgets.QDoubleSpinBox(self.group_cam)
        self.zEdit.setMinimum(-200.0)
        self.zEdit.setMaximum(200.0)
        self.zEdit.setObjectName("zEdit")
        self.gridLayout.addWidget(self.zEdit, 6, 2, 1, 1)
        self.yRotEdit = QtWidgets.QDoubleSpinBox(self.group_cam)
        self.yRotEdit.setMaximum(360.0)
        self.yRotEdit.setObjectName("yRotEdit")
        self.gridLayout.addWidget(self.yRotEdit, 4, 1, 1, 1)
        self.label_yrot = QtWidgets.QLabel(self.group_cam)
        self.label_yrot.setObjectName("label_yrot")
        self.gridLayout.addWidget(self.label_yrot, 2, 1, 1, 1)
        self.yEdit = QtWidgets.QDoubleSpinBox(self.group_cam)
        self.yEdit.setMinimum(-200.0)
        self.yEdit.setMaximum(200.0)
        self.yEdit.setObjectName("yEdit")
        self.gridLayout.addWidget(self.yEdit, 6, 1, 1, 1)
        self.xRotEdit = QtWidgets.QDoubleSpinBox(self.group_cam)
        self.xRotEdit.setMinimum(0.0)
        self.xRotEdit.setMaximum(360.0)
        self.xRotEdit.setObjectName("xRotEdit")
        self.gridLayout.addWidget(self.xRotEdit, 4, 0, 1, 1)
        self.label_x = QtWidgets.QLabel(self.group_cam)
        self.label_x.setObjectName("label_x")
        self.gridLayout.addWidget(self.label_x, 5, 0, 1, 1)
        self.label_zrot = QtWidgets.QLabel(self.group_cam)
        self.label_zrot.setObjectName("label_zrot")
        self.gridLayout.addWidget(self.label_zrot, 2, 2, 1, 1)
        self.bn_reset_cam = QtWidgets.QPushButton(self.group_cam)
        self.bn_reset_cam.setObjectName("bn_reset_cam")
        self.gridLayout.addWidget(self.bn_reset_cam, 1, 2, 1, 1)
        self.camCombo = QtWidgets.QComboBox(self.group_cam)
        self.camCombo.setObjectName("camCombo")
        self.gridLayout.addWidget(self.camCombo, 1, 0, 1, 2)
        self.layout_control.addWidget(self.group_cam)
        self.mainLayout.addWidget(self.widget_control)
        self.verticalLayout.addLayout(self.mainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 25))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuCapture = QtWidgets.QMenu(self.menubar)
        self.menuCapture.setObjectName("menuCapture")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionLoad_calibs = QtWidgets.QAction(MainWindow)
        self.actionLoad_calibs.setObjectName("actionLoad_calibs")
        self.actionRecord = QtWidgets.QAction(MainWindow)
        self.actionRecord.setObjectName("actionRecord")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionLoad_Skeletons = QtWidgets.QAction(MainWindow)
        self.actionLoad_Skeletons.setObjectName("actionLoad_Skeletons")
        self.actionConnectDB = QtWidgets.QAction(MainWindow)
        self.actionConnectDB.setObjectName("actionConnectDB")
        self.actionShow_Database_List = QtWidgets.QAction(MainWindow)
        self.actionShow_Database_List.setObjectName("actionShow_Database_List")
        self.actionLoadDB = QtWidgets.QAction(MainWindow)
        self.actionLoadDB.setObjectName("actionLoadDB")
        self.menuFiles.addAction(self.actionLoadDB)
        self.menuFiles.addAction(self.actionClear)
        self.menuCapture.addAction(self.actionRecord)
        self.menuCapture.addAction(self.actionStop)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuCapture.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Panoptic Studio Viewer"))
        self.bn_slow.setText(_translate("MainWindow", "..."))
        self.bn_play.setText(_translate("MainWindow", "..."))
        self.bn_fast.setText(_translate("MainWindow", "..."))
        self.label_frame.setText(_translate("MainWindow", "/"))
        self.bn_showcontrol.setText(_translate("MainWindow", "..."))
        self.group_model.setTitle(_translate("MainWindow", "Models"))
        self.group_cam.setTitle(_translate("MainWindow", "Camera"))
        self.label_y.setText(_translate("MainWindow", "y"))
        self.label_z.setText(_translate("MainWindow", "z"))
        self.label_xrot.setText(_translate("MainWindow", "xRot"))
        self.label_yrot.setText(_translate("MainWindow", "yRot"))
        self.label_x.setText(_translate("MainWindow", "x"))
        self.label_zrot.setText(_translate("MainWindow", "zRot"))
        self.bn_reset_cam.setText(_translate("MainWindow", "Reset"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuCapture.setTitle(_translate("MainWindow", "Capture"))
        self.actionLoad.setText(_translate("MainWindow", "Load Mesh"))
        self.actionLoad_calibs.setText(_translate("MainWindow", "Load calibs"))
        self.actionRecord.setText(_translate("MainWindow", "Record"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionLoad_Skeletons.setText(_translate("MainWindow", "Load Skeletons"))
        self.actionConnectDB.setText(_translate("MainWindow", "Connect to Database"))
        self.actionShow_Database_List.setText(_translate("MainWindow", "Show Dataset List"))
        self.actionLoadDB.setText(_translate("MainWindow", "Load"))

